#! /bin/sh
# chkconfig: 2345 10 90 
# description:  The memcached daemon is a network memory cache service.
# processname: memcached
# config: /etc/sysconfig/memcached

# Source function library.
. /etc/rc.d/init.d/functions

PORT=17406
PORT2=17407
PORT3=17408
USER=nobody
MAXCONN=40960
CACHESIZE=4096
#OPTIONS=""

OPTIONS=" -l 127.0.0.1  -U 0 "


if [ -f /etc/sysconfig/memcached ];then
    . /etc/sysconfig/memcached
fi

# Check that networking is up.
if [ "$NETWORKING" = "no" ]
then
    exit 0
fi

RETVAL=0
prog="memcached"

start () {
    echo -n $"Starting $prog: "
    # insure that /var/run/memcached has proper permissions
    chown $USER /mnt/hdisk/opt/memcache/bin/memcached
    daemon /mnt/hdisk/opt/memcache/bin/memcached -d -p $PORT -u $USER  -m $CACHESIZE -c $MAXCONN -P /var/run/memcached.pid $OPTIONS
    daemon /mnt/hdisk/opt/memcache/bin/memcached -d -p $PORT2 -u $USER  -m $CACHESIZE -c $MAXCONN -P /var/run/memcached2.pid $OPTIONS
    daemon /mnt/hdisk/opt/memcache/bin/memcached -d -p $PORT3 -u $USER  -m $CACHESIZE -c $MAXCONN -P /var/run/memcached3.pid $OPTIONS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/memcached
}
stop () {
    echo -n $"Stopping $prog: "
    killproc memcached
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ] ; then
        rm -f /var/lock/subsys/memcached
        rm -f /var/run/memcached.pid
        rm -f /var/run/memcached2.pid
        rm -f /var/run/memcached3.pid
    fi
}

restart () {
    stop
    start
}


# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
    stop
    ;;
    status)
    status memcached
    ;;
    restart|reload)
    restart
    ;;
    condrestart)
    [ -f /var/lock/subsys/memcached ] && restart || :
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
    exit 1
esac

exit $?

